.PHONY: all program1 program2 program3 program4 program5 program6
HOST = localhost
DATABASE = TTU 
USER = root
PASSWORD = coursework
export HOST DATABASE USER PASSWORD

all:
	make program1
	make program2
	#make program3
	#make program4
	#make program5
	#make program6

program1:
	make -C program1
program2:
	make -C program2
program3:
	make -C program3
program4:
	make -C program4
program5:
	make -C program5
program6:
	make -C program6

